sudo: required
services:
  - docker

before_install:
  - docker pull scartography/opensartoolkit:0.9.5

script:
  - docker run scartography/opensartoolkit:0.9.5 /bin/sh -c "export TRAVIS=$TRAVIS; pip3 uninstall -y ost; cd /home/ost; git clone https://github.com/EOX-A/OpenSarToolkit.git; cd OpenSarToolkit; git fetch; git checkout $TRAVIS_BRANCH --; git pull; python3 -m pip install ./; python3 -m pytest -v --cov=ost tests/;"

notifications:
  slack:
    rooms:
      - eox:SyjSUIKTXZg593pAn67N5M2h
      - opensartoolkit:yfJTtHP9vHW0Hp54LjEDrjH0
