# This workflow will build docker image and run tests on it (We need to use a custom image due to ESA SNAP Toolbox)
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build, Test and Push OST DockerImage

on:
  push:
    branches: [ master, gdal3, github_actions ]
  pull_request:
    branches: [ master ]

jobs:
  build_push_and_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        experimental: [ false ]
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, s1] # Needs to update git version on maplab to 2.9
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Prepare
      id: prep
      run: |
        DOCKER_IMAGE=scartography/opensartoolkit
        VERSION=${GITHUB_REF##*/}
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
        elif [[ $GITHUB_REF == refs/pull/* ]]; then
          VERSION=pr-${{ github.event.number }}
        fi
        TAGS="${DOCKER_IMAGE}:${VERSION}"
        if [ "${{ github.event_name }}" = "push" ]; then
          TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
        fi
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.prep.outputs.tags }}
        labels: |
          org.opencontainers.image.source=${{ github.event.repository.html_url }}
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.revision=${{ github.sha }}
        build-args: OST_BRANCH=${GITHUB_REF##*/}

    - name: Test at the docker image created
      env:
        CURL_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      run: |
        docker run scartography/opensartoolkit:${GITHUB_REF##*/} /bin/sh -c "pip3 uninstall -y ost; cd /home/jovyan/; git clone https://github.com/EOX-A/OpenSarToolkit.git; cd OpenSarToolkit; git fetch; git checkout ${GITHUB_REF##*/} --; git pull; python3 -m pip install .[test]; python3 -m pytest -v --cov=ost tests/;"

