# This workflow will build docker image and run tests on it (We need to use a custom image due to ESA SNAP Toolbox)
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build, Test and Push OST DockerImage

on:
  push:
    branches: [ master, gdal3, github_actions ]
  pull_request:
    branches: [ master ]

jobs:
  build_test_and_push:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        experimental: [ false ]
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, s1] # Needs to update git version on maplab to 2.9
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}

    - name: Build Newest Docker Image of this branch
      run: |
        docker build -t scartography/opensartoolkit:${GITHUB_REF##*/} ./

    - name: Test at the docker image created
      env:
        CURL_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      run: |
        docker run scartography/opensartoolkit:${GITHUB_REF##*/} /bin/sh -c "pip3 uninstall -y ost; cd /home/jovyan/; git clone https://github.com/EOX-A/OpenSarToolkit.git; cd OpenSarToolkit; git fetch; git checkout ${GITHUB_REF##*/} --; git pull; python3 -m pip install .[test]; python3 -m pytest -v --cov=ost tests/;"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: scartography/opensartoolkit/:${GITHUB_REF##*/}

