# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package test

on:
  push:
    branches: [ master, gdal3, github_actions ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        experimental: [ false ]
    runs-on: ubuntu-latest
    # runs-on :EOX_OpenSarToolkit
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}

    - name: Build Newest Docker Image of branch extract_branch
      run: |
        docker build -t scartography/opensartoolkit:${GITHUB_REF##*/} ./

    - name: Test at the docker image created
      env:
        CURL_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      run: |
        docker run -it scartography/opensartoolkit:${GITHUB_REF##*/} pytest -v --cov ost
    - name: Push docker image if tests are ok
      run: |
        docker push scartography/opensartoolkit:${GITHUB_REF##*/}

